# Generated by Django 3.0.8 on 2020-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('subject', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('action', models.CharField(choices=[('NEW', 'New'), ('SEEN', 'Seen'), ('ACCEPTED', 'Accepted'), ('IN PROGRESS', 'In Progress'), ('DONE', 'Done')], default='NEW', max_length=11)),
            ],
        ),
    ]
